### ISSUE TITLE
Can't scroll by dragging on the overlay

### ISSUE THREAD

**Issue by HugoMcPhee** [IjzerenHein/famous-flex-datepicker#1]
I'm using the date picker with both the global "famous-global.min.js" and "famous-flex-global.js" and if I create a DatePicker following the tutorial , with createRenderables top and bottom set to true, the scroll wheel can only be dragged from the middle of the two overlays (dragging on either the top or bottom overlay does nothing)

**Comment by IjzerenHein** [comment]
Hi, have you included the 'widgets/styles.css' file?
Cause this file contains a rule where it sets the 'pointer-events: none' for the top and bottom overlay renderables. This causes the events to be ignored for those surfaces and handled by the scrollwheel underneath.

**Comment by HugoMcPhee** [comment]
Hi  thanks! Thats what the issue was, I included it and it's working now

**Comment by IjzerenHein** [comment]
Awesome!
